<?php
echo '<div class="admission-form">';
echo '';
echo '<div class="company-title"><img src="img/logo/banner.jpg" alt="تصویر"></div>';
echo '';
echo '<div class="heading">';
echo '<p>داخلہ فارم</p>';
echo '</div>';
echo '<br>';
echo '';
echo '<div class="inner-box">';
echo '<div class="right">';
echo '<p>:مسلسل رجسٹر نمبر</p>';
echo '<p>:نام طالب علم/طالبہ</p>';
echo '<p>:جنس</p>';
echo '<p>:معزوری</p>';
echo '<p>:ولدیت</p>';
echo '<p>:قوم</p>';
echo '<p>:تاریخ پیدائش</p>';
echo '<p>:تاریخ داخلہ</p>';
echo '<p>:ماہانہ فیس</p>';
echo '<p>:مکمل رہائشی پتہ</p>';
echo '<p>:قومی شناختی کارڈ نمبر</p>';
echo '</div>';
echo '';
echo '<div class="left">';
echo '<div class="image"><img src="img/profile/default.jpg" alt="تصویر"></div>';
echo '<!-- <br class="b-r"><br class="b-r"><br class="b-r"><br class="b-r"><br class="b-r"><br class="b-r"><br class="b-r"><br class="b-r"><br class="b-r"> -->';
echo '<p>:تعلیمی قابلیت</p>';
echo '<p>:پیشہ</p>';
echo '<p>:مطلوبہ درجہ</p>';
echo '<p>:شعبہ</p>';
echo '<p>:موبائل نمبر دفتر</p>';
echo '<p>:موبائل نمبر گھر</p>';
echo '<p>:سابقہ مکتب کانام</p>';
echo '<p>:سابقہ مکتب کا پتہ</p>';
echo '<p>:سابقہ مکتب چھوڑنے کی وجہ</p>';
echo '';
echo '<p>:تعلیم کا وقت</p>';
echo '';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="line"></div>';
echo '';
echo '<div class="iftar-nama">';
echo '<h1>افترار نامہ</h1>';
echo '<table>';
echo '<tr>';
echo '<td>میں اقرا کرتا/کرتی ہوں کہ میرے علم کے مطابق مندرجہ بالاتفصیلات بلکل درست ہیں۔</td>';
echo '<td> .1</td>';
echo '</tr>';
echo '<tr>';
echo '<td>میں اپنے بیٹا / بیٹی کو مکتب کے قوانین وضوابط کی پانبدی کرواوٗں گا / کرواوٗں گی۔</td>';
echo '<td> .2</td>';
echo '</tr>';
echo '<tr>';
echo '<td>میں مکتب کی فیس اور دیگر تمام واجبات پابندی سے ادا کروں گا / کروں گی۔</td>';
echo '<td> .3</td>';
echo '</tr>';
echo '</table>';
echo '';
echo '</div>';
echo '';
echo '<div class="note">';
echo '<h1>نوٹ</h1>';
echo '<table>';
echo '<tr>';
echo '<td>والد یا سرپرست کے قومی شناختی کارڈکی کاپی ساتھ منسلک کریں۔</td>';
echo '<td> .1</td>';
echo '</tr>';
echo '<tr>';
echo '<td>مکتب کے قوانین کی خلاف ورزی کرنے پرمکتب کی انتظامیہ طالب علم / طالبہ کو مکتب سے خارج بھی کرسکتی ہے۔</td>';
echo '<td> .2</td>';
echo '</tr>';
echo '</table>';
echo '</div>';
echo '';
echo '<div class="office-use-only">';
echo '<h1>صرف دفتری استعمال کے لئے</h1>';
echo '<p> ناظم / ناظمہ کی رائے۔</p>';
echo '<p>___________________________________________________________________________________________________________________________________</p>';
echo '<p>___________________________________________________________________________________________________________________________________</p><br>';
echo '<p> :دستخط ناظم / ناظمہ</p>';
echo '';
echo '</div>';
echo '';
echo '</div>';
// else k bd
echo '<div class="alert-message">';
echo '<div class="alert alert-danger" style="text-align: center; font-size:20px;">';
echo '<strong>غلطی</strong>! مہربانی کر کہ دوباراہ کوشیش کریں۔ شکریہ ';
echo '<br> ' . $error_message;
echo '</div>';
echo '</div>';
