<?php
echo '<footer class="py-5">';
echo '<div class="container py-xl-4">';
echo '<div class="row footer-top">';
echo '<div class="col-lg-4 footer-grid_section_1its footer-text">';
echo '<!-- logo -->';
echo '<h2>';
echo '<a class="logo text-wh" href="index.html">';
echo '<!-- <img src="img/logo/ar.png" alt="Company Logo" class="img-fluid" style="width: 70px; height:70px;"> -->';
echo '</a>';
echo '</h2>';
echo '<!-- //logo -->';
echo '<h1 style="color: white; font-size:22px;">Andro Technologies</h1>';
echo '<p class="mt-lg-4 mt-3 mb-lg-5 mb-4">';
echo 'We are experts in Point of Sale softwares. We deliver high-quality products for your business. We are an experienced Designer, and Developer with a demonstrated history of working in the practical market industry. Expertise in attractive: Desktop or Mobile Application development and more as you want. Because we have the "Potential of learning & make the society Modernized"! Our Distinction: 100% Job Success with excellent client feedback Our Motto: Quality, Creativity, and the most important, Client, Satisfaction.';
echo '</p>';
echo '';
echo '</div>';
echo '<div class="col-lg-4 footer-grid_section_1its my-lg-0 my-sm-4 my-4">';
echo '<div class="footer-title">';
echo '<h3>Contact Us</h3>';
echo '</div>';
echo '<div class="footer-text mt-4">';
echo '<p>Address : Near Taj Masjid ARIST Tuition Center, Golimar Nawabshah, Pakistan.</p>';
echo '<p class="my-2">Phone : +92 305 8214945</p>';
echo '<p class="my-2">Phone : +92 311 4122990</p>';
echo '<p>Email : <a href="mailto:info@example.com">owais.quest@gmail.com</a></p>';
echo '</div>';
echo '</div>';
echo '<!-- <div class="col-lg-4 footer-grid_section_1its">';
echo '<div class="footer-title">';
echo '<h3>Request Info</h3>';
echo '</div>';
echo '<div class="info-form-right mt-4 p-0">';
echo '<form action="#" method="post">';
echo '<div class="row">';
echo '<div class="col-lg-6 form-group mb-2 pr-lg-1">';
echo '<input type="text" class="form-control" name="Name" placeholder="Name" required="">';
echo '</div>';
echo '<div class="col-lg-6 form-group mb-2 pl-lg-1">';
echo '<input type="text" class="form-control" name="Phone" placeholder="Phone" required="">';
echo '</div>';
echo '</div>';
echo '<div class="form-group mb-2">';
echo '<input type="email" class="form-control" name="Email" placeholder="Email" required="">';
echo '</div>';
echo '<div class="form-group mb-2">';
echo '<textarea name="Comment" class="form-control" placeholder="Comment" required=""></textarea>';
echo '</div>';
echo '<button type="submit" class="btn submit-contact ml-auto">Submit</button>';
echo '</form>';
echo '</div>';
echo '</div> -->';
echo '</div>';
echo '</div>';
echo '</footer>';
echo '<!-- //footer -->';
echo '<!-- copyright -->';
echo '<div class="cpy-right text-center py-3">';
echo '<p>© 2020 Madrasah Nafaais-ul-Quran-el-Kareem. All rights reserved | Developed by';
echo '<a href="https://www.androreviews.com/"> Andro Technologies.</a>';
echo '</p>';
echo '</div>';
echo '<!-- //copyright -->';
echo '<!-- move top icon -->';
echo '<a href="#home" class="move-top text-center">';
echo '<span class="fa fa-level-up" aria-hidden="true"></span>';
echo '</a>';
echo '<!-- //move top icon -->';
