<?php
echo '<div class="main-top py-1">';
echo '<div class="container">';
echo '<div class="nav-content">';
echo '<!-- logo -->';
echo '<h1>';
echo '<a id="logo" class="logo" href="http://localhost/pos/index.php">';
echo '<img src="http://localhost/pos/img/logo/logo.png" alt="" class="img-fluid" style="height: 50px; width: 50px;">';
echo '</a>';
echo '</h1>';
echo '<!-- //logo -->';
echo '<!-- nav -->';
echo '<div class="nav_web-dealingsls" style="font-weight: bold; font-size: 30px;">';
echo '<nav>';
echo '<label for="drop" class="toggle">Menu</label>';
echo '<input type="checkbox" id="drop" />';
echo '<ul class="menu">';
echo '<li><a href="http://localhost/pos/index.php">سرورق</a></li>';
echo '';
echo '<li>';
echo '<!-- Student Drop Down -->';
echo '<label for="drop-3" class="toggle toogle-2">طالب علم <span class="fa fa-angle-down" aria-hidden="true"></span>';
echo '</label>';
echo '<a href="#pages">طالب علم <span class="fa fa-angle-down" aria-hidden="true"></span></a>';
echo '<input type="checkbox" id="drop-3" />';
echo '<ul>';
echo '<li><a class="drop-text" href="http://localhost/pos/students/student-admission.php">طالب علم کا داخلہ</a></li>';
echo '<li><a class="drop-text" href="http://localhost/pos/students/student-filteration.php">فہرست طلباءکرام</a></li>';
echo '<li><a class="drop-text" href="http://localhost/pos/fees/pay-fees.php">فیس کی وصولی</a></li>';
echo '<li><a class="drop-text" href="http://localhost/pos/students/roll-number.php">رول نمبر</a></li>';
echo '</ul>';
echo '</li>';
echo '';
echo '';
echo '<li>';
echo '<!-- Student Drop Down -->';
echo '<label for="drop-3" class="toggle toogle-2">طالب علم <span class="fa fa-angle-down" aria-hidden="true"></span>';
echo '</label>';
echo '<a href="#pages">فیس <span class="fa fa-angle-down" aria-hidden="true"></span></a>';
echo '<input type="checkbox" id="drop-3" />';
echo '<ul>';
echo '<li><a class="drop-text" href="http://localhost/pos/fees/pay-fees.php">فیس کی وصولی</a></li>';
echo '<li><a class="drop-text" href="http://localhost/pos/fees/fees-receive-information.php">فیس کی تفصیل</a></li>';
echo '</ul>';
echo '</li>';
echo '';
echo '<li>';
echo '<!-- Teacher Drop Down -->';
echo '<label for="drop-3" class="toggle toogle-2">معلمین و ملازمین<span class="fa fa-angle-down" aria-hidden="true"></span>';
echo '</label>';
echo '<a href="#pages">معلمین و ملازمین<span class="fa fa-angle-down" aria-hidden="true"></span></a>';
echo '<input type="checkbox" id="drop-3" />';
echo '<ul>';
echo '<li><a class="drop-text" href="http://localhost/pos/teachers/teacher-admission.php">معلمین و ملازمین تقرر فارم</a></li>';
echo '<li><a class="drop-text" href="http://localhost/pos/teachers/teacher-filteration.php">فہرست معلمین و ملازمین</a></li>';
echo '<li><a class="drop-text" href="http://localhost/pos/salary/pay-salary.php">رجسٹر مشاہرہ</a></li>';
echo '<li><a class="drop-text" href="http://localhost/pos/salary/salary-give-information.php">تنخواہ ادا ئیگی معلومات</a></li>';
echo '</ul>';
echo '</li>';
echo '';
echo '<li>';
echo '<!-- Examination Drop Down -->';
echo '<label for="drop-3" class="toggle toogle-2">ہاضریاں<span class="fa fa-angle-down" aria-hidden="true"></span>';
echo '</label>';
echo '<a href="#pages">حاضریاں<span class="fa fa-angle-down" aria-hidden="true"></span></a>';
echo '<input type="checkbox" id="drop-3" />';
echo '<ul>';
echo '<li><a class="drop-text" href="http://localhost/pos/attendance/attendance.php">حاضری</a></li>';
echo '<li><a class="drop-text" href="http://localhost/pos/attendance/attendance-filter.php">حاضری رجسٹر</a></li>';
echo '</ul>';
echo '</li>';
echo '';
echo '<li>';
echo '<!-- Examination Drop Down -->';
echo '<label for="drop-3" class="toggle toogle-2">امتحان <span class="fa fa-angle-down" aria-hidden="true"></span>';
echo '</label>';
echo '<a href="#pages">امتحان<span class="fa fa-angle-down" aria-hidden="true"></span></a>';
echo '<input type="checkbox" id="drop-3" />';
echo '<ul>';
echo '<li><a class="drop-text" href="http://localhost/pos/examination/exam-entry.php" َََ>نتیجہ امتحان داخلہ</a></li>';
echo '<li><a class="drop-text" href="http://localhost/pos/examination/exam-filteration.php">نتیجہ امتحان</a></li>';
echo '<li><a class="drop-text" href="http://localhost/pos/examination/exam-card-print.php">نتیجہ امتحان پرینٹ</a></li>';
echo '</ul>';
echo '</li>';
echo '';
echo '<li>';
echo '<!-- Fainantial Drop Down -->';
echo '<label for="drop-3" class="toggle toogle-2">آمدن  / تفصیل خرچ <span class="fa fa-angle-down" aria-hidden="true"></span>';
echo '</label>';
echo '<a href="#pages">تفصیل آمدن / تفصیل خرچ<span class="fa fa-angle-down" aria-hidden="true"></span></a>';
echo '<input type="checkbox" id="drop-3" />';
echo '<ul>';
echo '<li><a class="drop-text" href="http://localhost/pos/finance/financial.php">آمدن و اخرجات</a></li>';
echo '<li><a class="drop-text" href="http://localhost/pos/finance/finance-filteration.php">آمدن و اخرجات تفصیلات</a></li>';
echo '</ul>';
echo '</li>';
echo '';
echo '</ul>';
echo '</nav>';
echo '</div>';
echo '<!-- //nav -->';
echo '</div>';
echo '</div>';
echo '</div>';
